CREATE TABLE IF NOT EXISTS culture (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  cultureGroup TEXT NOT NULL
);

INSERT INTO culture (id, name, cultureGroup) VALUES
('norse', 'Norse', 'North Germanic'),
('swedish', 'Swedish', 'North Germanic'),
('danish', 'Danish', 'North Germanic'),
('norwegian', 'Norwegian', 'North Germanic'),
('saxon', 'Saxon', 'West Germanic'),
('frankish', 'Frankish', 'West Germanic'),
('bavarian', 'Bavarian', 'West Germanic'),
('occitan', 'Occitan', 'Latin'),
('french', 'French', 'Latin'),
('italian', 'Italian', 'Latin'),
('sardinian', 'Sardinian', 'Latin'),
('castillan', 'Castillan', 'Iberian'),
('andalusian', 'Andalusian', 'Iberian'),
('basque', 'Basque', 'Iberian'),
('irish', 'Irish', 'Goidelic'),
('scottish', 'Scottish', 'Goidelic'),
('welsh', 'Welsh', 'Brythonic'),
('breton', 'Breton', 'Brythonic'),
('greek', 'Greek', 'Byzantine'),
('armenian', 'Armenian', 'Byzantine'),
('georgian', 'Georgian', 'Byzantine'),
('bedouin', 'Bedouin', 'Arabic'),
('mashriqi', 'Mashriqi', 'Arabic'),
('persian', 'Persian', 'Iranian'),
('kurdish', 'Kurdish', 'Iranian'),
('afghan', 'Afghan', 'Iranian'),
('czech', 'Czech', 'West Slavic'),
('polish', 'Polish', 'West Slavic'),
('croatian', 'Croatian', 'South Slavic'),
('serbian', 'Serbian', 'South Slavic'),
('bulgarian', 'Bulgarian', 'South Slavic'),
('russian', 'Russian', 'East Slavic'),
('finnish', 'Finnish', 'Uralic'),
('magyar', 'Magyar', 'Uralic'),
('turkic', 'Turkic', 'Altaic'),
('mongol', 'Mongol', 'Altaic');